generator/src/templates/deploy.bash.twig
Ticket: https://spryker.atlassian.net/browse/SC-1811
=> SC-1811: Providing arguments form bash to api test console command

generator/src/templates/deploy.bash.twig
Ticket: https://spryker.atlassian.net/browse/SC-1816
=> SC-1816: deleted extra networks from arguments

generator/src/templates/deploy.bash.twig, sdk
- Ticket: https://spryker.atlassian.net/browse/SC-1817
=> SC-1817: Update command list to contain project specific items

generator/src/templates/deploy.bash.twig, generator/src/templates/docker-compose.test.xdebug.yml.twig, generator/src/templates/docker-compose.test.yml.twig
- Developer(s): @alexanderM91 
- Ticket: https://spryker.atlassian.net/browse/SC-1917
- Release Group: https://release.spryker.com/release-groups/view/1902
- Suite-nonsplit: https://github.com/spryker/suite-nonsplit/pull/2866
DockerSdk         | minor                 |                       |
Updated Docker SDK help.
Improvements
- Adjusted Docker SDK help function. Renamed from `codecept` to `testing`.
=> SC-1917: Update help

generator/src/templates/deploy.bash.twig, generator/src/templates/docker-compose.test.xdebug.yml.twig, generator/src/templates/docker-compose.xdebug.yml.twig, generator/src/templates/env/cli/store.env.twig, generator/src/templates/env/cli/testing.env.twig
- Developer(s): @sprymiker  
- Ticket: https://spryker.atlassian.net/browse/SC-1917
- Release Group: https://release.spryker.com/release-groups/view/1909
DockerSdk         | patch                 |                       |
Adjusted Docker SDK Xdebug.
Bugfixes
- Adjusted debug session to determinate properly.
=> SC-1874: Docker: PHPStorm does not determinate Spryker debug session

context/elasticsearch/elasticsearch.yml, generator/src/templates/service/elastic.yml.twig
- Ticket: https://spryker.atlassian.net/browse/SC-2026
- Release Group: https://release.spryker.com/release-groups/view/1981
Bugfixes
- Fixed execution of console command `search:snapshot:register-repository`.
=> SC-2026: Snapshot register leads to error

images/swagger/Dockerfile
- Ticket: https://spryker.atlassian.net/browse/SC-2368
- Release Group: https://release.spryker.com/release-groups/view/2027
- Swagger - demo mode. RestApi schema generation.
=> SC-2092: Demo mode, swagger file generation

context/kibana/kibana.yml, generator/src/templates/nginx/http/kibana.server.conf.twig, generator/src/templates/nginx/tcp/elastic.server.conf.twig, generator/src/templates/nginx/tcp/rabbitmq.server.conf.twig, generator/src/templates/service/kibana.yml.twig, images/kibana/Dockerfile
- Ticket: https://spryker.atlassian.net/browse/SC-2287
- Suite-Nonsplit PR: https://github.com/spryker/suite-nonsplit/pull/3105
- Release Group: https://release.spryker.com/release-groups/view/2053
- Introduced a new Kibana service for Docker Environment.
- Introduced a new TCP ElasticSearch server configuration.
- Introduced a new TCP RabbitMq server configuration.
=> SC-2287: Expose ES and RMQ ports + kibana service

generator/src/templates/application-volumes.yml.twig
- Ticket: https://spryker.atlassian.net/browse/SC-2419
- Release Group: https://release.spryker.com/release-groups/view/2059
- Adjusted PHP configuration path in the application volumes.
=> SC-2419: Updated the path to php.ini

bin/boot-deployment.sh, bin/check-directories.sh, bin/check-project-directory.sh, ci/check_boot.sh, sdk
- Ticket: https://spryker.atlassian.net/browse/SC-1850
- Release Group: https://release.spryker.com/release-groups/view/2069
- Prevent the usage of spaces in the project path and project name.
=> SC-1850: Directory spaces is not supported

bin/assets/baked.sh
Ticket: https://spryker.atlassian.net/browse/SC-2639
=> SC-2639: "No such file or directory" error - during moving assets from temp directory

bin/assets/baked.sh, bin/export-helper.sh
Ticket: https://spryker.atlassian.net/browse/SC-2640
=> SC-2640: Generation assets doesn't work if the destination folder wasn't created before generation

generator/src/templates/deploy.bash.twig
Ticket: https://spryker.atlassian.net/browse/SC-2612
RG: https://release.spryker.com/release-groups/view/2295
- Adjusted command descriptions into `docker/sdk help`
=> SC-2612: Add "images" word in the description of the command: docker/sdk help

generator/src/templates/deploy.bash.twig
- Developer(s): @alexanderM91 
- Ticket: https://spryker.atlassian.net/browse/SC-1983
- Release Group: https://release.spryker.com/release-groups/view/2353
DockerSdk         | patch                 |                       |
{none}
Bugfixes
- Fixed the possibility to run the application without assets volume.
=> Create assets volume

bin/mount/docker-sync.sh, generator/src/templates/deploy.bash.twig
- Developer(s): @zyuzka  
- Ticket: https://spryker.atlassian.net/browse/SC-2614
- Release Group: https://release.spryker.com/release-groups/view/2363
DockerSdk         | patch                 |                       |
{none}
Bugfixes
- Fixed files synchronization for docker-sync.
=> SC-2614: Dev mode (docker-sync) doesn`t work with ES6

bin/build/mount.sh, bin/images/baked.sh, bin/images/mount.sh, generator/src/templates/deploy.bash.twig, images/base_app/Dockerfile
- Developer(s): @alexanderM91 
- Ticket: https://spryker.atlassian.net/browse/SC-2614
- Release Group: https://release.spryker.com/release-groups/view/2363
- Suite-Nonsplit PR: https://github.com/spryker/suite-nonsplit/pull/3549
DockerSdk         | minor                 |                       |
{none}
Improvements
- Introduced a new functionality to handle composer arguments using the DockerSDK  configuration.
=> SC-2733: Controlling --no-dev option

bin/install.sh, bin/mount/nfs.sh, bin/nfs/get-project-path.sh, generator/index.php, generator/src/templates/deploy.bash.twig, sdk
Tiket: https://spryker.atlassian.net/browse/SC-2708
=> SC-2708: Notification is shown when extra configuration is needed (sudo)

.known_hosts, bin/boot-deployment.sh, bin/images/baked.sh, bin/images/mount.sh, generator/index.php, generator/src/templates/deploy.bash.twig, images/base_app/Dockerfile, images/base_dev/Dockerfile
- Ticket: https://spryker.atlassian.net/browse/SC-2566
- RG: https://release.spryker.com/release-groups/view/2401
Implemented functionality for a generation `.ssh/known_hosts` into containers on `build` step
=> SC-2566: ".ssh/known_hosts" should be updated with ssh github.com command

generator/src/templates/service/mysql/5.7/mysql.yml.twig
Ticket: https://spryker.atlassian.net/browse/SC-2525
RG: https://release.spryker.com/release-groups/view/2391
- FIxed static MySql port binding.
=> SC-2525: Error during run app in dev mode if MySql was set 3306 port in deploy.dev.yml

generator/src/templates/deploy.bash.twig
- Ticket: https://spryker.atlassian.net/browse/SC-2274
- RG: https://release.spryker.com/release-groups/view/2481
- Fixed the behavior when docker container(s) cannot be stopped on Unix-like operating systems.
=> SC-2274: Can't stop docker containers

bin/assets/baked.sh, images/builder_assets/Dockerfile, images/cli/demo/Dockerfile, images/cli/dev/Dockerfile
Ticket: https://spryker.atlassian.net/browse/SC-2895
=> SC-2895: Docker images have Debian as base distro

bin/assets/baked.sh, images/builder_assets/Dockerfile, images/cli/demo/Dockerfile, images/cli/dev/Dockerfile
Epic: https://spryker.atlassian.net/browse/SC-2894
RG: https://release.spryker.com/release-groups/view/2487
- Introduced Denian support as a base image.
=> SC-2894: Docker images have Debian as base distro

bin/images/baked.sh, bin/images/mount.sh, generator/index.php, generator/src/templates/application/glue.yml.twig, generator/src/templates/application/yves.yml.twig, generator/src/templates/application/zed.yml.twig, generator/src/templates/deploy.bash.twig, generator/src/templates/docker-compose.yml.twig, generator/src/templates/env/common.env.twig, generator/src/templates/php/conf.d/99-from-deploy-yaml-php.ini.twig, generator/src/templates/service/blackfire/default/blackfire.yml.twig, images/base_app/Dockerfile, images/base_dev/Dockerfile, images/cli/demo/Dockerfile, images/cli/dev/Dockerfile
Ticket: https://spryker.atlassian.net/browse/SC-2676
=> SC-2676: support newrelic

.dockerignore.default, bin/export-helper.sh, bin/images/baked.sh, bin/images/mount.sh, generator/index.php, generator/src/templates/deploy.bash.twig, generator/src/templates/docker-compose.yml.twig, generator/src/templates/env/common.env.twig, generator/src/templates/service/blackfire/1.34.0/blackfire.yml.twig, generator/src/templates/service/blackfire/default/blackfire.yml.twig, images/base_app/Dockerfile, images/base_dev/Dockerfile, images/builder_assets/Dockerfile, images/cli/demo/Dockerfile, images/cli/dev/Dockerfile
Epic: https://spryker.atlassian.net/browse/SC-2661
- Added Blackfire support.
- Added NewRelic support.
=> SC-2661: Support blackfire

generator/index.php
Ticket: https://spryker.atlassian.net/browse/SC-3062
=> SC-3062: Refactoring after requirements changes

bin/build/baked.sh, bin/build/mount.sh, bin/images/baked.sh, bin/images/main.sh, bin/images/mount.sh, generator/index.php, generator/src/templates/application/glue.yml.twig, generator/src/templates/application/yves.yml.twig, generator/src/templates/application/zed.yml.twig, generator/src/templates/deploy.bash.twig, generator/src/templates/images/main/Dockerfile.twig, images/base_app/Dockerfile, images/base_dev/Dockerfile
Ticket: https://spryker.atlassian.net/browse/SC-3083
=> SC-3083: Refatoring

README.md, generator/src/templates/service/postgres/10/postgres.yml.twig, generator/src/templates/service/postgres/11/postgres.yml.twig, generator/src/templates/service/postgres/12/postgres.yml.twig, generator/src/templates/service/postgres/default/postgres.yml.twig
Ticket: https://spryker.atlassian.net/browse/SC-3061
RG: https://release.spryker.com/release-groups/view/2682
- Introduced support for PostgreSQL versions: 10, 11 and 12.
=> SC-3061: PostgreSQL 10/11/12 is supported

generator/index.php, generator/src/templates/docker-compose.yml.twig, generator/src/templates/nginx/http/redis-commander.server.conf.twig, generator/src/templates/service/redis-commander/default/redis-commander.yml.twig
- Ticket: https://spryker.atlassian.net/browse/SC-2994
- RG: https://release.spryker.com/release-groups/view/2626
- Introduced GUI to access Redis databases and perform some basic operations using RedisCommander.
=> SC-2294: RedisGui

generator/src/templates/deploy.bash.twig
Ticket: https://spryker.atlassian.net/browse/SC-2569
RG: https://release.spryker.com/release-groups/view/2685
- Increased wait time for all services.
=> SC-2569: spryker_b2c_dev_broker_1 has unhealthy status during "docker/sdk up"

images/base_app/Dockerfile
Ticket: https://spryker.atlassian.net/browse/SC-2979
RG: https://release.spryker.com/release-groups/view/2696
- Fixed the behavior when the copying data process executes after the building stage.
=> SC-2979: Installation happens before project's data is copied

generator/index.php, generator/openssl/generate.sh
- Ticket: https://spryker.atlassian.net/browse/SC-3126
- RG: https://release.spryker.com/release-groups/view/2718
- Fixed the behavior with a self-signed certificate on the Linux when the browser rejects some requests.
=> SC-3127: Document how to use TLS locally

generator/index.php
- Ticket: https://spryker.atlassian.net/browse/SC-4036
- RG: https://release.spryker.com/release-groups/view/2813
- Adjusted terraform `frontend.json` with a new `zone` parameter which contains the second-level domain name.
=> SC-4036: Second level domain for teraform generation

generator/src/templates/service/elastic/7.6/elastic.yml.twig
Ticket: https://spryker.atlassian.net/browse/TE-4700
RG: https://release.spryker.com/release-groups/view/2851
=> Added template for ES7

generator/index.php, generator/src/templates/docker-compose.test.yml.twig, images/common/application/Dockerfile.twig, images/mount/application/Dockerfile
Ticket: https://spryker.atlassian.net/browse/SC-4086
RG: https://release.spryker.com/release-groups/view/2856
=> SC-4086: Docker SDK: Testing mode leads to fatal error on Yves

context/php/debug/etc/debug.php-fpm.d/worker.conf, generator/src/templates/nginx/conf.d/debug.default.conf.twig, generator/src/templates/nginx/conf.d/frontend.default.conf.twig, generator/src/templates/nginx/http/gateway/server.conf.twig, generator/src/templates/nginx/http/glue.server.conf.twig, generator/src/templates/nginx/http/yves.server.conf.twig, generator/src/templates/nginx/http/zed.server.conf.twig, generator/src/templates/nginx/vhost.d/glue.default.conf.twig, generator/src/templates/nginx/vhost.d/timeouts.conf.twig, generator/src/templates/nginx/vhost.d/yves.default.conf.twig, generator/src/templates/nginx/vhost.d/zed.default.conf.twig
Ticket: https://spryker.atlassian.net/browse/SC-4334
Suite PR: https://github.com/spryker/suite-nonsplit/pull/4436
=> SC-4334: Increased timeouts in Nginx and PHP for requests with XDebug

generator/src/templates/nginx/conf.d/gateway.default.conf.twig, generator/src/templates/nginx/http/gateway/server.conf.twig
Ticket: https://spryker.atlassian.net/browse/SC-4053
RG: https://release.spryker.com/release-groups/view/2857
=> SC-4053: Docker SDK does not properly support websockets

bin/command/compose/up.sh, generator/src/templates/env/cli/store.env.twig, generator/src/templates/env/cli/testing.env.twig, generator/src/templates/nginx/http/glue.server.conf.twig, generator/src/templates/nginx/http/server.conf.twig, generator/src/templates/nginx/http/yves.server.conf.twig, generator/src/templates/nginx/http/zed.server.conf.twig
Ticket: https://spryker.atlassian.net/browse/CC-10469
RG: https://release.spryker.com/release-groups/view/2934
=> CC-10469: Fixing PORT environment variables in SSL mode

context/dashboard/package-lock.json, context/dashboard/package.json
- Ticket/Issue: https://github.com/spryker/docker-sdk/issues/140
- Updated vulnerable dependency: bl
=> Issue 140: Updated vulnerable dependency (bl)

ci/deploy.dev.yml, ci/deploy.yml, generator/src/templates/env/application/glue.env.twig, generator/src/templates/env/application/yves.env.twig, generator/src/templates/env/application/zed.env.twig, generator/src/templates/env/cli/store.env.twig, generator/src/templates/env/mail/mail.env.twig, generator/src/templates/env/scheduler/jenkins.env.twig, generator/src/templates/nginx/http/glue.server.conf.twig, generator/src/templates/nginx/http/yves.server.conf.twig, generator/src/templates/nginx/http/zed.server.conf.twig, generator/src/templates/terraform/application/glue.tf.twig, generator/src/templates/terraform/application/yves.tf.twig, generator/src/templates/terraform/application/zed.tf.twig, generator/src/templates/terraform/mail/mail.tf.twig
Ticket: https://spryker.atlassian.net/browse/SC-4606
=> SC-4606: Adding the possibility to set sender email/name via deploy.yml.

generator/composer.json, generator/composer.lock, generator/index.php, generator/src/templates/nginx/http/static.server.conf.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-4820
- RG: https://release.spryker.com/release-groups/view/2982
- Fixed extra redirection when using redirect attribute in SSL mode
=> SC-4820: Fixed extra redirection when using redirect attribute in SSL mode

bin/command/deploy.sh, bin/sdk/compose.sh, bin/sdk/images/common.sh, bin/standalone/cli.sh, generator/src/templates/deploy.bash.twig, generator/src/templates/docker-compose.yml.twig, generator/src/templates/nginx/conf.d/debug.default.conf.twig, generator/src/templates/nginx/conf.d/gateway.default.conf.twig, images/common/dashboard/Dockerfile, images/common/services/tideways/Dockerfile, images/debug/application/Dockerfile, images/debug/cli/Dockerfile, images/debug/frontend/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-4805
- Added possibility to disable xdebug images and modes mainly for CI/CD and testing.
=> SC-4805: Added possibility to disable xdebug images and modes

.travis.yml
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-4965
- Adjusted Travis CI with a BC jobs for public B2C and B2B demoshops.
=> BC check for public B2C and B2B demoshops

generator/index.php, generator/src/templates/env/common.env.twig, generator/src/templates/terraform/broker/rabbitmq.tf.twig, generator/src/templates/terraform/database/mysql.tf.twig, generator/src/templates/terraform/database/postgres.tf.twig, generator/src/templates/terraform/environment.common.tf.twig, generator/src/templates/terraform/secrets.sdk.auto.tfvars.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-4653
- RG: https://release.spryker.com/release-groups/view/3028
- Added SSH keys generation for OAuth during bootstrap.
- Added random token generation for OAuth during bootstrap.
- Added random token generation for ZedRequest during bootstrap.
=> SC-4745: Added keys and token generator for auth purposes

bin/sdk/images/common.sh, generator/src/templates/deploy.bash.twig, images/baked/application/Dockerfile, images/common/application-local/Dockerfile, images/debug/application/Dockerfile, images/debug/cli/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-4925
- https://release.spryker.com/release-groups/view/3035
- Fixed SSL self-signed certificate issue in non-debug mode.
=> SC-4925: Fixed SSL self-signed certificate issue in non-debug mode

ci/deploy.dev.yml, ci/deploy.yml, generator/index.php, generator/src/templates/nginx/http/gateway/static.server.conf.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-5277
- Suite PR:
- Fixed the missing template for a static application.
=> SC-5277: Fixed the missing template for a static application.

context/php/php.ini
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-4080
- Adjusted PHP runtime `max_input_vars` configuration parameter.
=> SC-4080: Increase max_input_vars input variable

bin/service/broker/rabbitmq.sh
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-5692
- 
- Fixed issue with TTY for setting RabbitMQ vhosts
=> SC-5692: Fixed issue with TTY for setting RabbitMQ vhosts

images/baked/application/Dockerfile, images/common/cli/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-4300
=> SC-4300: Add Yarn to dev docker image

generator/src/templates/nginx/conf.d/frontend.default.conf.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-5758
- Suite:
- Adjusted nginx `server_names_hash_bucket_size` to support long domain names
=> SC-5758: Adjusted nginx `server_names_hash_bucket_size` to support long domain names

generator/src/templates/nginx/conf.d/frontend.default.conf.twig, images/baked/application/Dockerfile, images/common/cli/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-5758
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-4300
- Adjusted nginx `server_names_hash_bucket_size` to support long domain names.
- Added Yarn into CLI docker image.
=> [SC-4300 | SC-5758]: Adjusted nginx `server_names_hash_bucket_size` and Yarn support

generator/index.php
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-5791
- Fixed wrong escaping for environment variables.
=> SC-5791: Check behavior of json_encode in oauth token generation script(docker-sdk)

docs/06-installation/02-installation-guides/03-installing-in-demo-mode.md, docs/99-deploy.file.reference.v1.md
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-5987
In `docs/99-deploy.file.reference.v1.md`, replaced tabs with spaces.
- [v] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
=> Replace tabs with spaces in the deploy file reference

generator/src/templates/service/rabbitmq/3.7/rabbitmq.yml.twig
=> Update RabbitMQ hostname explanation

docs/02-development/05-configuring-debugging.md
https://spryker.atlassian.net/browse/SC-6173
Xdebug 3 is out and requires a new configuration. 
* Adjusted Xdebug configuration in PhpStorm
* Added Xdebug configuration for VScode
- [v] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
=> Updated debugging configuration instructions

README.md, generator/src/templates/service/mysql/mariadb-10.5/mysql.yml.twig
- Introduced `MariaDB 10.5` version support.
=> MariaDB 10.5 support

docs/05-configuring-access-to-private-repositories.md, generator/index.php
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-6081
=> SC-6081: Check docker sdk boot

README.md
- Ticket/Issue: https://spryker.atlassian.net/browse/AC-1137
We are unifying readme files in our repositories.
Adjusted readme.md
- [v] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
=> AC-1137: Updated README.md

images/baked/assets/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-6662
- Fixed assets permissions.
=> SC-6662: Fixed permission error for frontend-related assets.

bin/sdk/images/common.sh
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-6520
- Introduce a new pipeline image
=> SC-6521: Introduce a new pipeline image

context/php/debug/etc/debug.php-fpm.d/worker.conf, context/php/php-fpm.d/worker.conf, docs/99-deploy.file.reference.v1.md, generator/src/templates/env/application/glue.env.twig, generator/src/templates/env/application/yves.env.twig, generator/src/templates/env/application/zed.env.twig, generator/src/templates/env/pm/php-fpm.env.twig, generator/src/templates/terraform/application/glue.tf.twig, generator/src/templates/terraform/application/yves.tf.twig, generator/src/templates/terraform/application/zed.tf.twig, generator/src/templates/terraform/pm/php-fpm.tf.twig, images/common/application/Dockerfile.twig, images/debug/application/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-6518
- Introduce the possibility to define PHP workers per application.
=> SC-6518: Define PHP worker per application

docs/06-installation/02-installation-guides/01-choosing-an-installation-mode.md, docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md, docs/06-installation/02-installation-guides/03-installing-in-development-mode-on-windows.md, docs/06-installation/02-installation-guides/04-installing-in-demo-mode-on-macos-and-linux.md, docs/06-installation/02-installation-guides/05-installing-in-demo-mode-on-windows.md, docs/06-installation/02-installation-guides/06-integrating-the-docker-sdk-into-existing-projects.md, docs/09-troubleshooting.md, docs/10-configuration-reference.md, docs/99-deploy.file.reference.v1.md
- Ticket: https://spryker.atlassian.net/browse/SC-6256
=> SC-5500: Separate endpoints. Docs follow up.

docs/99-deploy.file.reference.v1.md
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-4808
* Updated the description of the parameter per the epic.
* Fixed minor bugs
- [x ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md
=> Fix minor bugs 99-deploy.file.reference.v1.md

generator/index.php
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-7186
- Fixed incorrect application endpoint camel case name.
=> SC-7186: EntryPoint has incorect case

generator/src/templates/nginx/conf.d/frontend.default.conf.twig, generator/src/templates/nginx/conf.d/gateway.default.conf.twig, generator/src/templates/nginx/http/default.location.conf.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SCO-3262
- Disabled `server tokens` directive in the Nginx.
- Removed `X-server` response header.
=> SCO-3262: Disable server token directive for Nginx

context/dashboard/package-lock.json, context/dashboard/package.json
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-7591
- updated `path-parse` dependency for `Dashboard`
=> SC-7591: Dependabot alerts

images/common/cli/Dockerfile, images/common/services/tideways/Dockerfile, images/debug/application/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-7608
- https://github.com/spryker/docker-php/pull/31
=> SC-7608: Debian. Replace apt-get with apt.

generator/index.php, generator/src/templates/env/cli/testing.env.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-7508
- Fixed generation of the testing.env.
=> SC-7508: testing.env is not generated if yves app does not exist

docs/06-configuring-services.md, docs/99-deploy.file.reference.v1.md, generator/index.php
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-7610
- Suite Nonsplit PR: https://github.com/spryker/suite-nonsplit/pull/5836
- Docker-PHP PR: https://github.com/spryker/docker-php/pull/33
- adjusted Newrelic configuration with distributed tracing
- updated documentation
=> SC-7610: Trace ZED API Calls in New Relic

.travis.yml
- Run Docker process in `before_install` step.
=> TravisCI. Run Docker service in before script.

docs/09-troubleshooting.md
- Troubleshooting page extension.
=> Docs. DB pot is occupied

generator/src/templates/nginx/entrypoint.sh.twig, images/common/frontend/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-7829
- Fixed the behaviour when SPRYKER_DNS_RESOLVER_IP is not defined.
=> Nginx. Optional DNS resolver ip

docs/99-deploy.file.reference.v1.md, generator/src/templates/env/common.env.twig, generator/src/templates/service/blackfire/latest/blackfire.yml.twig, images/common/cli/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-6926
- https://github.com/spryker/docker-php/pull/32
- Support of Blackfire v2.
=> Support of Blackfire v2

docs/09-troubleshooting.md
- Ticket: https://spryker.atlassian.net/browse/SC-7499
- Troubleshooting document extension for `docker/sdk` cli case. For example command execution:  `docker/sdk cli composer require spryker/*`
=> SC-7499: Troubleshooting

docs/07-deploy-file/01-deploy-file.md, docs/07-deploy-file/03-deploy-file-inheritance-common-use-cases.md
- Ticket/Issue: [](https://spryker.atlassian.net/browse/SC-7704)
Follow-up fixes for docs
- 
Updated the description of parameter inheritance
=> Sc 8089/deploy file inheritance follow up

bin/sdk/images/common.sh, generator/src/templates/nginx/entrypoint.sh.twig, images/common/frontend/Dockerfile, images/debug/frontend/Dockerfile
- Ticket: https://spryker.atlassian.net/browse/SC-8619
- Fixed Nginx incorrect behavior when debug mode is enabled.
=> [SC-8619] Frontend cannot be started when debug mode is enabled

context/dashboard/package-lock.json, docs/06-installation/02-installation-guides/01-choosing-an-installation-mode.md, docs/07-deploy-file/01-deploy-file.md, docs/07-deploy-file/02-deploy.file.reference.v1.md, docs/07-deploy-file/03-deploy-file-inheritance-common-use-cases.md, docs/09-troubleshooting.md, generator/deploy-file-generator/src/DeployFileGeneratorConstants.php, generator/deploy-file-generator/src/Importer/DataImporter.php, generator/deploy-file-generator/src/ParametersResolver/Resolvers/AbstractAnnotationParameterResolver.php, generator/deploy-file-generator/src/Processor/Executor/PreExecutors/PrepareDeployFileTransferExecutor.php, generator/deploy-file-generator/tests/unit/DeployFileGeneratorTest/Processor/Executor/PreExecutors/PrepareDeployFileTransferExecutorTest.php, generator/index.php, generator/src/templates/application/glue-backend.yml.twig, generator/src/templates/application/glue-storefront.yml.twig, generator/src/templates/env/application/glue-backend.env.twig, generator/src/templates/env/application/glue-storefront.env.twig, generator/src/templates/env/cli/store.env.twig, generator/src/templates/nginx/http/gateway/glue-backend.server.conf.twig, generator/src/templates/nginx/http/gateway/glue-storefront.server.conf.twig, generator/src/templates/nginx/http/glue-backend.server.conf.twig, generator/src/templates/nginx/http/glue-storefront.server.conf.twig, generator/src/templates/nginx/vhost.d/glue-backend.default.conf.twig, generator/src/templates/nginx/vhost.d/glue-storefront.conf.twig, generator/src/templates/terraform/application/glue-backend.tf.twig, generator/src/templates/terraform/application/glue-storefront.tf.twig
=> updating docker branch with the latest inheritance

generator/src/templates/nginx/entrypoint.sh.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-8635
- Fixed replacement of environment variable for the debug configuration.
=> Nginx. Env var is not defined

docs/07-deploy-file/01-deploy-file.md, docs/07-deploy-file/02-deploy.file.reference.v1.md, docs/07-deploy-file/03-deploy-file-inheritance-common-use-cases.md, generator/deploy-file-generator/src/DeployFileGeneratorConstants.php, generator/deploy-file-generator/src/Importer/DataImporter.php, generator/deploy-file-generator/src/ParametersResolver/Resolvers/AbstractAnnotationParameterResolver.php, generator/deploy-file-generator/src/Processor/Executor/PreExecutors/PrepareDeployFileTransferExecutor.php, generator/deploy-file-generator/tests/unit/DeployFileGeneratorTest/Processor/Executor/PreExecutors/PrepareDeployFileTransferExecutorTest.php
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-8536
- Introduced the possibility to import the same file multiple times.
- Fixed replacement for more than one parameter in one line inside import file.
=> SC-8536: Multiple import of the same file

context/redis/redis.conf, generator/src/templates/service/redis/5.0/redis.yml.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/ALO-314
- Increased Redis database number from 16 to 64.
=> AOL-314: Increate number of Redis dbs from 16 to 64

generator/src/templates/env/application/backend-gateway.env.twig, generator/src/templates/env/application/backoffice.env.twig, generator/src/templates/env/application/merchant-portal.env.twig, generator/src/templates/nginx/conf.d/frontend.default.conf.twig, generator/src/templates/terraform/application/backend-gateway.tf.twig, generator/src/templates/terraform/application/backoffice.tf.twig, generator/src/templates/terraform/application/merchant-portal.tf.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-8815
- Added missed PHP-FPM configuration.
=> SC-8815: Added missed PHP-FPM configuration

docs/07-deploy-file/01-deploy-file.md, docs/07-deploy-file/03-deploy-file-inheritance-common-use-cases.md, generator/deploy-file-generator/src/DeployFileGeneratorFactory.php, generator/deploy-file-generator/src/Exception/ParameterFilterNotExistException.php, generator/deploy-file-generator/src/ParameterFilter/Filters/LowerCaseParameterFilter.php, generator/deploy-file-generator/src/ParameterFilter/Filters/UpperCaseParameterFilter.php, generator/deploy-file-generator/src/ParameterFilter/ParameterFilterInterface.php, generator/deploy-file-generator/src/ParametersResolver/Resolvers/AbstractAnnotationParameterResolver.php, generator/deploy-file-generator/tests/unit/DeployFileGeneratorTest/ParametersResolver/Resolvers/PercentAnnotationParameterResolverTest.php
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-8611
- Introduced lower and upper case filters for dynamic parameters.
=> SC-8611: Dynamic parameters filter

generator/src/templates/nginx/http/static.conf.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SCO-33908
- Adjusted Nginx configuration with publicly available `/assets/*` location.
=> SCO-33908: Assets location allow all

context/dashboard/package-lock.json, context/dashboard/package.json
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-8896
- updated `bl` and `dockerode` packages for `dashboard`
=> SC-8896: Fix dependency alerts

generator/src/templates/terraform/environment.common.tf.twig
=> Remove extra quotes

generator/src/templates/service/chromedriver/default/chromedriver.yml.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-9067
- Update ChromeDriver to the latest version.
=> Update ChromeDriver to the latest version

bin/sdk/mount/mutagen.sh
- Ticket/Issue: https://spryker.atlassian.net/browse/PPLUS-1250
Fixes
- Fixed compatibility with Mutagen 0.14.0
=> Fixed compatibility with Mutagen 0.14.0

bin/environment/docker-compose.sh
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-9281
- Fixed incompatibility with Docker Compose 2.5.0
=> Fix Docker Compose 2.5.0 incompatibility

README.md, bin/environment/docker-compose.sh, bin/service/broker/rabbitmq.sh, bin/service/scheduler/jenkins.sh, context/kibana/6.8/kibana.yml, generator/index.php, generator/src/templates/service/elastic/5.6/elastic.yml.twig, generator/src/templates/service/elastic/6.8/elastic.yml.twig, generator/src/templates/service/kibana/5.6/kibana.yml.twig, generator/src/templates/service/kibana/6.8/kibana.yml.twig, generator/src/templates/service/mailhog/1.0/mailhog.yml.twig, generator/src/templates/service/redis-commander/0.8.0/redis-commander.yml.twig, generator/src/templates/service/redis-commander/default/redis-commander.yml.twig, generator/src/templates/service/swagger-ui/v3.24/swagger-ui.yml.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-9317
- Introduced support of ES 5.6 and 6.8 under ARM architecture. 
- Introduced support of Kibana 5.6 and 6.8 under ARM architecture.
- Introduced support of Swagger-UI v3.24.3 under ARM architecture.
- Introduced support of Redis-Commander 0.8.0 under ARM architecture.
- Introduced support of Mailhog v1.0.0 under ARM architecture.
- Fixed long response from rabbit and Jenkins services (TTY issue)
=> Introduced support of ARM architecture for services.

bin/sdk/data/demo.sh
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-9433
- fixed wrong current store env variable for US region
=> SC-9433: docker/sdk up imports demo-data for US each time

generator/src/templates/nginx/http/application.server.conf.twig, generator/src/templates/nginx/http/proxy/reverse-proxy.conf.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-9633
=> SC-9633: Proxy-pass

bin/sdk/images/common.sh, docs/07-deploy-file/02-deploy.file.reference.v1.md, generator/deploy-file-generator/config/validation.yml, generator/deploy-file-generator/src/Validator/Rule/RangeValueRule.php, generator/index.php, generator/src/templates/deploy.bash.twig, images/common/application/Dockerfile.twig, images/common/cli/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-9516
- adjusted deploy file for configuration NodeJS version
- adjusted deploy file for configuration Npm version
- adjusted deploy file for configuration distribution of Node image
- adjusted docs
=> SC-9516: Configure NPM and Node version from deploy.*.yaml

generator/index.php
- https://spryker.atlassian.net/browse/TE-10998
- added token generating for environment variable `SPRYKER_URI_SIGNER_SECRET_KEY`.
=> TE-10998 Replaced static URL sign secret with ENV key

generator/deploy-file-generator/templates/environment/ci/assets.deploy.template.yml
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-10171
- b2b-internal: https://github.com/spryker/b2b-demo-shop-internal/pull/1616
- b2b-marketplace-internal: https://github.com/spryker/b2b-demo-marketplace-internal/pull/20
- b2c-internal: https://github.com/spryker/b2c-demo-shop-internal/pull/1155
- b2c-marketplace-internal: https://github.com/spryker/b2c-demo-marketplace-internal/pull/169
- nonsplit: https://github.com/spryker/suite-nonsplit/pull/7002
- brotli: https://github.com/spryker/docker-nginx-brotli/pull/1
- updated assets template with spryker/brotli usage
=> SC-10171: Broken install process in production mode on M1

generator/index.php
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-10185
- Fixed generator for missed application.
=> Adjust generator with check of missed application

docs/06-installation/01-installation-prerequisites/01-installing-docker-prerequisites-on-macos.md, docs/06-installation/01-installation-prerequisites/02-installing-docker-prerequisites-on-linux.md, docs/06-installation/01-installation-prerequisites/03-installing-docker-prerequisites-on-windows.md, docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md, docs/06-installation/02-installation-guides/03-installing-in-development-mode-on-windows.md, docs/06-installation/02-installation-guides/04-installing-in-demo-mode-on-macos-and-linux.md, docs/06-installation/02-installation-guides/05-installing-in-demo-mode-on-windows.md, docs/06-installation/02-installation-guides/06-integrating-the-docker-sdk-into-existing-projects.md
- Minimum requirements adjustments
=> [Docs] Minimum requirements adjustments

bin/sdk/images/baked/ecr.sh
=> [BUG] Push to ECR

bin/sdk/images/baked/ecr.sh, images/common/services/jenkins/export/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-10419
- Added `latest` tag for ECR push strategy.
=> [SC-10419]: ECR push image with the latest tag.

docs/01-quick-start-guide.md, docs/02-development/01-choosing-a-mount-mode.md, docs/02-development/06-running-tests.md, docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md, docs/06-installation/02-installation-guides/03-installing-in-development-mode-on-windows.md, docs/06-installation/02-installation-guides/04-installing-in-demo-mode-on-macos-and-linux.md, docs/06-installation/02-installation-guides/05-installing-in-demo-mode-on-windows.md, docs/06-installation/02-installation-guides/06-integrating-the-docker-sdk-into-existing-projects.md, docs/07-deploy-file/02-deploy.file.reference.v1.md, docs/09-troubleshooting.md
This pull request
🤷 To be honest, it's a bit disappointing that the documentation is in such a bad shape. We are paying customer of Spryker, and when we ask support, they often point to the documentation.
=> Fix: References

README.md
Link in README.md to deploy file documentation is broken
=> Update link to deploy file

images/common/services/jenkins/export/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-10005
- Fixed Jenkins version to 2.361.1 to fix security vulnerabilities.
=> [SC-10005] Update Jenkins version.

generator/deploy-file-generator/config/validation.yml, generator/deploy-file-generator/src/Validator/DeployFileValidatorFactory.php, generator/deploy-file-generator/src/Validator/Rule/OrRule.php, generator/deploy-file-generator/templates/environment/ci/assets.deploy.template.yml
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-8908
- implemented new validation rule : OR condition
=> SC-8908: Deploy file validation. OR condition

bin/platform.sh
Issue: https://spryker.atlassian.net/browse/SC-5621
- Makes platform detection for WSL2 case-insensitive
=> SC-5621: Makes platform detection for WSL2 case-insensitive

bin/service/database/postgres.sh
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-11155
Issue: 
- https://github.com/spryker/docker-sdk/issues/380
- Fixed tables condition check for PostgreSQL database.
=> SC-11155 GitHub Action - service cli is not running container

docs/07-deploy-file/04-installation-recipes-of-deployment-pipelines.md
- Ticket: https://spryker.atlassian.net/browse/SC-11036
- Issue: https://github.com/spryker/docker-sdk/issues/374
* Added document with explanation for installation recipes
=> SC-11036 Key sections is not explained for installation recipes

bin/command/install/bootstrap.sh, generator/index.php
- Adjusted generation of the node base image name.
=> Hotfix. Debian. CI

generator/index.php
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-11653
- Dynamic secrets for the product configuration.
=> SC-11653: Dynamic secrets for product configurator

README.md, generator/deploy-file-generator/templates/environment/ci/services.deploy.template.yml, generator/deploy-file-generator/templates/environment/demo/services.deploy.template.yml, generator/deploy-file-generator/templates/environment/dev/services.deploy.template.yml, generator/src/templates/service/redis/6.2/redis.yml.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-10027
- RG: https://release.spryker.com/release-groups/view/4388
- added Redis 6.2 support
=> SC-10027: Upgrade Redis to version 6.2

bin/command/install/install.sh
Ticket: https://spryker.atlassian.net/browse/SDK-1583
=> SDK-1583: Fix typo in console output

context/jenkins/export/entrypoint.sh
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-12276
- Jenkins. Remove old Jenkins plugins
=> [SC-12276]: Remove old Jenkins all plugins

bin/command/install/bootstrap.sh, bin/command/install/config.sh, bin/environment/docker.sh
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-12425
- RG: https://release.spryker.com/release-groups/view/4663
- removed `--progress` argument from building generator image
=> SC-12425: Prepare Docker/SDK to new Docker engine version(v23)

README.md, generator/src/templates/service/mysql/mariadb-10.6/mysql.yml.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-12451
- Introduced support of MariaDB 10.6
=> Introduced support of MariaDB 10.6

bin/command/install/bootstrap.sh, bin/command/install/config.sh
- Extended help with a `boot` alias for `boostrap` command.
=> Extended help with `boot` command

bin/sdk/data/demo.sh, bin/service/service.sh
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-12623
- ensuring that CLI is running when we are loading data
=> [SC-12623] [CI] Service `cli` is not running container

context/jenkins/export/entrypoint.sh
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-13145
- Removed the condition for checking the existence of `nr-credentials.xml` file for Jenkins image.
=> SC-13145 Jenkins backed images (remove condition for nr-credentials.xml)

generator/index.php
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-13258
- Fixed `SPRYKER_OAUTH_CLIENT_CONFIGURATION` environment variable formatting.
=> SC-13258 fixed SPRYKER_OAUTH_CLIENT_CONFIGURATION formatting.

README.md
- Updated ReadMe with MariaDB EOL status for 10.2 and 10.3 versions.
=> Update README.md, supported services section with Mariadb EOL status

generator/src/templates/service/elastic/7.10/elastic.yml.twig, generator/src/templates/service/opensearch/1.3/opensearch.yml.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-13408
- https://github.com/spryker-projects/docker-elasticsearch
- https://github.com/spryker-projects/docker-opensearch
- using spryker/elasticsearch:7.10
- using spryker/opensearch:1.3
=> Custom images for spryker/elasticsearch:7.10 and spryker/opensearch:1.3

images/common/services/jenkins/export/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-13578
- change the security repository for Debian into Jenkins service
=> [SC-13578] Update security repository for Debian into Jenkins service

bin/command/compose/exec.sh, bin/command/compose/ps.sh, bin/command/compose/up.sh, bin/sdk/compose.sh, generator/src/templates/deploy.bash.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-13335
- Introduced `docker/sdk exec` command to execute a command for the specified service from the `docker/sdk ps`.
=> Introduced docker/sdk exec command to execute a command for the specific service

generator/src/templates/nginx/http/merchant-portal.server.conf.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-13731
- added environment variable SPRYKER_MP_HOST for merchant portal 
- fixed environment variable SPRYKER_BE_HOST for merchant portal
=> SC-13731 SPRYKER_MP_HOST missed or mixed with SPRYKER_BE_HOST into the merchant portal 

.github/workflows/b2b-b2c-demo-shop-tests.yml, generator/src/templates/deploy.bash.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-14953
- https://github.com/spryker/docker-sdk/issues/457
- Fixed progress bar with new docker version
=> SC-14953: [Github Actions] Failed to get console during docker/sdk up

generator/src/templates/terraform/e2e/e2e.tf.twig
- Ticket/Issue:  https://spryker.atlassian.net/browse/SC-15051
- Fix an issue when it does not generate TF block for E2E pipeline.
=> E2E pipeline has incorrect endpoints list

generator/src/templates/service/redis/5.0/redis.yml.twig, generator/src/templates/service/redis/6.2/redis.yml.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-13850
- https://github.com/spryker/suite-nonsplit/pull/8152
- updated healthcheck for Redis
=> SC-13850 Check key-value container healthcheck command

generator/index.php
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-15041
- https://github.com/spryker/docker-php/pull/77
- Adjusted `buildNewrelicDistributedTracing` with array key exist
=> SC-15298 Support Alpine 3.18

generator/src/templates/nginx/http/glue-backend.server.conf.twig, generator/src/templates/nginx/http/glue.server.conf.twig, generator/src/templates/nginx/http/server.conf.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-13903
=> SC-13903 Global visibility of cors-allow-origin leads to issues of ovewritten value for different entry-points in nginx config

docs/07-deploy-file/02-deploy.file.reference.v1.md, generator/src/templates/nginx/conf.d/frontend.default.conf.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-17065
- Introduced support of the CIDR format for IPs for maintenance whitelist.
=> SC-17065: CIDR support for the maintenance mode

docs/06-installation/01-installation-prerequisites/01-installing-docker-prerequisites-on-macos.md
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-17030
- https://github.com/spryker/spryker-docs/pull/2291
- Added description for Orbstack usage instead of Docker Desktop
=> [DOCS] [SC-17030]: Orbstack

context/dashboard/package-lock.json
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-17846
- Fixed Dashboard security vulnerability
=> SC-17846: Dashboard security vulnerability

context/dashboard/package-lock.json, context/dashboard/package.json
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-17846
- Fixed Dashboard security vulnerability
=> SC-17846: Fix security vulnerability for dashboard

README.md, generator/src/templates/service/jenkins/2.442/jenkins.yml.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-18434
- Support of Jenkins 2.442
=> SC-18434: Jenkins 2.442 support

bin/command/install/bootstrap.sh
- fixed one typo ... yieha
iy <> yi
=> fixed small typo :)

generator/src/templates/terraform/mail/mail.tf.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-19174
- Optional `SPRYKER_MAIL_SENDER_EMAIL` and `SPRYKER_MAIL_SENDER_NAME` environment variables inside `environment.tf`
=> SC-19174: Optional mail configuration inside env.tf

context/dashboard/package-lock.json, context/dashboard/package.json
- Dashboard. Fixed security vulnerability
=> Dashboard. Vulnerability fix

images/baked/application/Dockerfile
This PR adds the bin folder to the docker image
=> Added bin folder to docker image

bin/command/install/bootstrap.sh, bin/command/install/config.sh
=> Fix missing args for SPRYKER_PHP_IMAGE causing CI failures

.github/workflows/trivy.yml, .github/workflows/trufflehog.yml, .trivy/.trivyignore.yaml, .trivy/trivy.yaml, .trufflehog/.trufflehogignore.txt
https://spryker.atlassian.net/browse/SC-21611
Enabling trivy and trufllehog that will scan repo for secret leakage
=> Enabling trivy and trufflehog

bin/command/install/bootstrap.sh, bin/environment/mutagen-version-check.sh, docs/09-troubleshooting.md
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-21724
- Introduced `Mutagen v0.18.*` version check. 
- Updated Troubleshooting page with Mutagen v0.18.* installation error.
=> Mutagen v0.18.* check

generator/index.php
Ticket: https://spryker.atlassian.net/browse/CC-34832
=> CC-34832 Moved generation of customer remember me secret to docker generator.

bin/sdk/images/baked/ecr.sh
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-21892
- Push images to ECR in parallel
=> Push ECR images in parallel

bin/command/install/bootstrap.sh, docs/02-development/02-environment-variables.md, generator/src/templates/application/backend-gateway.yml.twig, generator/src/templates/application/backoffice.yml.twig, generator/src/templates/application/glue-backend.yml.twig, generator/src/templates/application/glue.yml.twig, generator/src/templates/application/merchant-portal.yml.twig, generator/src/templates/application/yves.yml.twig, generator/src/templates/application/zed.yml.twig
- Introduced support for the `.env` file for local development.
=> Introduced support of the .env for the local development

.github/workflows/trufflehog.yml
https://spryker.atlassian.net/issues/SC-22147
Disabling online secrets validation by trufflehog to prevent suspicious activity from AWS
non applicable
non applicable
=> Disabling online secrets validation by trufflehog to prevent suspicious activity from AWS

docs/07-deploy-file/02-deploy.file.reference.v1.md, generator/src/templates/nginx/http/application.server.conf.twig, generator/src/templates/nginx/http/buffer.server.conf.twig, generator/src/templates/nginx/http/redirects/redirects.conf.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-22509
- Nginx redirects
- Nginx buffer configuration
=> SC-22508: Nginx configuration improvements

context/otel-stack/dashboards/dashboard-top.json, context/otel-stack/grafana-dashboards.yaml, context/otel-stack/grafana-datasources.yaml, context/otel-stack/otel-collector.yaml, context/otel-stack/prometheus.yaml, context/otel-stack/tempo.yaml, docs/06-configuring-services.md, generator/src/templates/nginx/http/gateway/otel-stack.server.conf.twig, generator/src/templates/service/otel-stack/default/otel-stack.yml.twig, generator/src/templates/service/otel-stack/latest/otel-stack.yml.twig
=> Otel integration

README.md, generator/src/templates/service/jenkins/2.492.3/jenkins.yml.twig, images/common/services/jenkins/export/Dockerfile
- Ticket/Issue: https://spryker.atlassian.net/browse/FRW-10224
- Introduced Jenkins 2.492.3
=> Jenkins 2.492.3

generator/src/templates/service/jenkins/2.401/jenkins.yml.twig, generator/src/templates/service/jenkins/2.442/jenkins.yml.twig, generator/src/templates/service/jenkins/2.488/jenkins.yml.twig, generator/src/templates/service/jenkins/2.492.3/jenkins.yml.twig, generator/src/templates/service/jenkins/2.504.1/jenkins.yml.twig, generator/src/templates/service/rabbitmq/3.10/rabbitmq.yml.twig, generator/src/templates/service/rabbitmq/3.11/rabbitmq.yml.twig, generator/src/templates/service/rabbitmq/3.12/rabbitmq.yml.twig, generator/src/templates/service/rabbitmq/3.13/rabbitmq.yml.twig, generator/src/templates/service/redis/6.2/redis.yml.twig
=> Aldi CICS-67022; update templates with CI variable

bin/command/install/bootstrap.sh, docs/07-deploy-file/02-deploy.file.reference.v1.md, generator/Dockerfile, images/baked/application/Dockerfile, images/baked/cli/Dockerfile, images/baked/frontend/Dockerfile, images/common/application-local/Dockerfile, images/common/application/Dockerfile.twig, images/common/cli/Dockerfile, images/common/dashboard/Dockerfile, images/common/frontend/Dockerfile, images/common/services/jenkins/export/Dockerfile, images/debug/application/Dockerfile, images/debug/cli/Dockerfile, images/debug/frontend/Dockerfile
=> Enable OSX trusted certificates to be copied into docker Container

generator/src/templates/nginx/entrypoint.sh.twig
- Ticket/Issue: https://spryker.atlassian.net/browse/SC-23688
- Fix incorrect `SPRYKER_DNS_RESOLVER_IP` resolving
=> Fix wrong SPRYKER_DNS_RESOLVER_IP
