bin/boot-deployment.sh
bin/check-docker-machine.sh

Ticket: https://spryker.atlassian.net/browse/SC-2085
RG: https://release.spryker.com/release-groups/view/2294
Updated boot functionality for providing correct `user_uid` and `user_gid` on Linux with docker-machine

SC-2085: "docker/sdk boot" lead to error if docker-machine are using on Linux env

---

bin/boot-deployment.sh
bin/build/mount.sh
generator/src/templates/application-volumes.yml.twig
generator/src/templates/deploy.bash.twig
generator/src/templates/docker-sync.yml.twig

- Ticket: https://spryker.atlassian.net/browse/SC-2840
- RG: https://release.spryker.com/release-groups/view/2441
- Allow using a custom image for docker-sync. 
- Unison's strategy changed from `prefer` to `force`. 
- Permission for binaries is now set before installation script.
- Mount mode for sync volume changed to `nocopy`
- The direct mount for the composer cache has been removed.

SC-2840: Docker SDK: Multiple issues on Windows

---

README.md
generator/src/templates/service/kibana/6.8/kibana.yml.twig

Developer(s): @alexanderM91 
- Ticket: https://spryker.atlassian.net/browse/SC-2855
- Release Group: https://release.spryker.com/release-groups/view/2451
DockerSdk         | minor                 |                       |
{none}
- Support Kibana version 6.

SC-2855: Support kibana 6

---

README.md
generator/src/templates/service/mysql/mariadb-10.2/mysql.yml.twig
generator/src/templates/service/mysql/mariadb-10.3/mysql.yml.twig
generator/src/templates/service/mysql/mariadb-10.4/mysql.yml.twig

- Ticket: https://spryker.atlassian.net/browse/SC-3085
- RG: https://release.spryker.com/release-groups/view/2695
- Introduced support for `MariaDB` versions: 10.2, 10.3, and 10.4.

 SC-3085: MariaDB v10.2-4 is supported

---

generator/openssl/v3.ext

- Ticket: https://spryker.atlassian.net/browse/SC-3131
- RG: https://release.spryker.com/release-groups/view/2700
- Fixed generation of the apple valid server certs by adding ExtendedKeyUsage (EKU) extension containing the id-kp-serverAuth OID.

SC-3131: Generate apple valid cert

---

generator/src/templates/nginx/conf.d/frontend.default.conf.twig
generator/src/templates/nginx/entrypoint.sh.twig

Ticket: https://spryker.atlassian.net/browse/SC-4026
RG: https://release.spryker.com/release-groups/view/2837
Create new environment variable which contains hostname and port
for the specific php application. For backwards compatibility the
value defaults to the "old" hostname environment variable with
the default fastcgi port 9000
TBD

SC-3990: Make port to fastcgi application configurable

---

bin/standalone/cli.sh

- https://spryker.atlassian.net/browse/SC-4827
- https://stackoverflow.com/questions/55591009/bin-bash-i-overwrites-ps1
- Fixed wrong prompt in CLI on debian-based image

SC-4827: Fixed wrong prompt in CLI on debian-based image

---

generator/index.php
generator/src/templates/nginx/http/glue.server.conf.twig

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-4807
- Added possibility to set `CORS allow origin` value via deploy.yml. Glue endpoints can be enhanced with `cors-allow-origin` property in order to propagate `SPRYKER_GLUE_APPLICATION_CORS_ALLOW_ORIGIN` environment variable.
- Changed default value of `SPRYKER_GLUE_APPLICATION_CORS_ALLOW_ORIGIN` from "*" to "" in the sake of security.
- Possible BC breaks for projects that use Glue endpoints from a browser application. Can be fixed by adding the application URL in deploy.yml files.

SC-4807: Added possibility to set CORS allow origin value via deploy.yml

---

generator/index.php
generator/src/templates/nginx/conf.d/debug.default.conf.twig
generator/src/templates/nginx/conf.d/frontend.default.conf.twig
generator/src/templates/nginx/conf.d/gateway.default.conf.twig
generator/src/templates/nginx/http/gateway/server.conf.twig
generator/src/templates/nginx/vhost.d/glue.default.conf.twig
generator/src/templates/nginx/vhost.d/yves.default.conf.twig
generator/src/templates/nginx/vhost.d/zed.default.conf.twig

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-5142
- RG: https://release.spryker.com/release-groups/view/3081
- Introduced `groups: applications: http: max-request-body-size:` to be set per an application and defines maximum allowed request body size for all requests to the application.

SC-5142: Introduced `max-request-body-size` to be set per application

---

images/common/cli/Dockerfile

- Sets NPM version to 6 for BC reason for Debian OS.

Stick NPM to 6 version for BC

---

context/php/debug/etc/php/debug.conf.d/69-xdebug.ini
docs/02-development/05-configuring-debugging.md

- Ticket: https://spryker.atlassian.net/browse/SC-6114
PHP started to install XDebug version 3 by default. `docker/sdk` did not have a proper configuration for this specific version.
- https://xdebug.org/docs/upgrade_guide
- Adjusted XDebug configuration to work with XDebug v3.

SC-6114: Fixed Xdebug v3 debugging mode.

---

docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md
docs/06-installation/02-installation-guides/03-installing-in-development-mode-on-windows.md
docs/06-installation/02-installation-guides/04-installing-in-demo-mode-on-macos-and-linux.md
docs/06-installation/02-installation-guides/05-installing-in-demo-mode-on-windows.md
docs/06-installation/02-installation-guides/06-integrating-the-docker-sdk-into-existing-projects.md

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-7065
- Adjusted installation section with dynamic hosts set up based on deploy file.

[SC-7065]: Documentation adjustments. Installation section

---

context/php/debug/etc/php/debug.conf.d/69-xdebug.ini

- Ticket/Issue: #184
The `coverage` mode is needed in order to run the test coverage analysis
<https://xdebug.org/docs/all_settings#mode>
Enabled `coverage` xdebug mode

Enable coverage xdebug.mode

---

bin/lib/version.sh

Currently fails with input like "11.8.0" (running bash5 on MacOS Catalina) with a "value too great for base" error as the leading zeros make bash interpret the number as octagonal.
- Ticket: 
- Forced Version::parse to interpret given version as a decimal

Fix Version::parse interpreting number as octagonal

---

generator/src/templates/nginx/http/backoffice.server.conf.twig

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-7521
- Extended `backoffice` Nginx configuration with `merchant-portal` fastcgi params: `SPRYKER_MP_HOST`  and `SPRYKER_MP_PORT` if `merchant-portal` application is defined.

[SC-7521] Extend Backoffice with MerchantPortal host and port

---

generator/index.php

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-6985
- Fixed the possibility to override debug configuration via deployment file using of php.ini section.

SC-6985: Impossible to override php.ini for debugging via deployment file

---

bin/command/build/baked/build.sh
bin/command/build/baked/export.sh
bin/command/build/mount/build.sh
bin/command/install/bootstrap.sh
bin/command/install/install.sh
sdk

- Ticket/Issue: #181 
All occurrences of `/de/stderr` replaced with `>&2`. The `/dev/stderr` doesn't always exist.
More details:
https://www.sichong.site/2020/01/09/dev-stdout-vs-2-a-dive-into-linux-stdio/
Replaced `>/dev/stderr` with `>&2`

Replace /dev/stderr with &2

---

bin/sdk/mount/mutagen.sh

On MAC OS sometimes there is a syncronisation issue after restart of the Docker-Desktop due to an obsolete mutagen session(s). 
Usually this problem arises after restart of the MAC OS, because it restarts the Docker-Desktop.
This mutagen problem under MAC OS is known and described: https://github.com/mutagen-io/mutagen/issues/243
The only suggestion in the issue is to delete the mutagen sessions automatically in a startup script: https://github.com/mutagen-io/mutagen/issues/243#issuecomment-868470834.
In such a case Spryker officially suggests to delete the Mutagen sessions manually: https://documentation.spryker.com/docs/mutagen-synchronization-issue
That suggestion from Spryker takes time of every Spryker developer under MAC OS, who restarts the OS.
The PR provides automatical deletion …

To avoid sync issue on MAC OS - delete mutagen sessions with obsolete docker id

---

generator/src/templates/nginx/conf.d/debug.default.conf.twig

Fix typo in `debug.default.conf.twig`: Variable zedEndpoint is not existing, probably a typo and `zedHost` was meant, which at least leads to passing the correct port to the `$application.server.conf.twig` template (normally port 1001).
- Fixed incorrect host in the debug configuration.

Fix typo in debug.default.conf.twig

---

bin/environment/docker-compose.sh

With newer Version docker the "docker-compose version --short" command gives out a version number string with "v" at the beginning, so the later comparison failed with this misleading error message:  
`Docker Compose version v2.1.1 is not supported. Please update Docker Compose to at least 1.22.0. `
With the help of "tr" to remove the leading "v" will fix this problem.
- 
-

Fix docker-compose version check bug.

---

generator/src/templates/nginx/entrypoint.sh.twig
generator/src/templates/nginx/http/static.conf.twig

- Ticket/Issue:  https://spryker.atlassian.net/browse/SC-8485
- Fixed assets inaccessibility with assets fallback location for Nginx configuration based on the current value of the `SPRYKER_BUILD_HASH` environment variable.

SC-8485: Assets are not available during production deployment

---

bin/sdk/images/common.sh

- Ticket: https://spryker.atlassian.net/browse/SC-6350
- Issue: https://github.com/spryker/docker-sdk/issues/188
- adjusted `clean` function for dropping all spryker images

SC-6350: docker-sdk clean does not remove all images

---

bin/standalone/cli-rpc.js

This PR fixes wrong build status and missing task output in Jenkins jobs.
1. Fixed response code in cli-rpc.js (cli-rpc responded with 200 instead of 400, because response.statusCode must be set before any response.write).
2. Transfer STDERR output with cli-rpc.js (missing output in jenkins)

Fix CLI RPC status code and output

---

context/redis/redis.conf

- Ticket/Issue: https://spryker.atlassian.net/browse/ALO-314
- Increased the default number of Redis databases from 64 to 1024.

Increase the default number of Redis databases from 64 to 1024

---

generator/index.php

SDK uses '*.local' as TLD, which needs customized host entries in '/etc/hosts'.
I  use '*.localhost' as local TLD for my Spryker Shop services, like 'yves.de.b2c.development.localhost'.
Then I do not need an installer instruction like 'Please add these host entires to /etc/hosts'.
So the requirement is:
When using '*.localhost' as tld domain name for a host the host name shall also (like 'localhost itself) not be included in the hosts-array created by the 'Installer::hosts' boot step.
Ref: ./docker/bin/installer/hosts.sh
At MMS we use '*.localhost' as local TLD for our services, like 'yves.de.b2c.env-1.localhost'.
We use multiple environments concurrently at one docker site (e.g. a WSL2) with multiple applications (b2c, b2b, suite, our own's...) and tear them up and down quickly and …

feat(): disable 'Installer::hosts' for all '*.localhost' TLDs, not only 'localhost'

---

generator/src/templates/env/common.env.twig
generator/src/templates/terraform/environment.common.tf.twig
generator/src/templates/terraform/store.env.twig

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-7329
- Introduced `SPRYKER_ACTIVE_STORES` environment variable which contains the list of active stores per region.

SC-7329: Provide environment variable with the list of active stores

---

docs/06-configuring-services.md
docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md
generator/index.php

- Ticket/Issue:  https://spryker.atlassian.net/browse/SC-8863
- Original PR: https://github.com/spryker/docker-sdk/pull/292
- Adjusted host-helper functionality for excluded *.localhost hosts from /etc/hosts update-message

SC-8863: Endpoints with .localhost do not require update of /etc/hosts

---

docs/07-deploy-file/02-deploy.file.reference.v1.md
generator/src/templates/nginx/http/static.server.conf.twig

- Ticket/Issue: https://spryker.atlassian.net/browse/SCO-35211
- Fixed the behaviour when `$request_uri` doesn't preserve via redirects for the `static` application type.

SCO-35211: Preserve $request_uri via redirects for `static` application type

---

bin/command/internal/prune.sh

- https://spryker.atlassian.net/browse/SC-9184
- Introduced `--f` argument in `docker/sdk prune` command for skipping prompt questions.

SC-9184: Force argument for `docker/sdk prune`

---

generator/src/templates/terraform/environment.common.tf.twig

- fixed double-quotes typo for SPRYKER_JENKINS_CSRF_PROTECTION_ENABLED env variables

Removed unnecessary double quotes for SPRYKER_JENKINS_CSRF_PROTECTION_ENABLED env variable

---

context/php/php-fpm.d/worker.conf

- RN-286: https://spryker.atlassian.net/browse/RN-286
Logs in AWS are cut at 1024 char. There is no way to set this as unlimited, so I put [the limit from aws](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html) for PutLogEvents.
I requested a confirmation from the PHP team: https://github.com/php/php-src/issues/9010
Eventhough I still don't know why 512.
- fix log cuts for AWS CloudWatch at 1024 chars

RN-286: fix log cuts for AWS CloudWatch at 1024 chars

---

images/common/cli/Dockerfile

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-10114
- added sys packages for npm8 on ARM

SC-10114: NPM library is incompatible with Docker on Mac with Apple chip

---

bin/platform.sh

- Revert WSL2 case insensitive detection due to synchronization issue on the Windows OS.

Revert WSL2 case insensitive detection

---

generator/src/templates/nginx/http/glue-storefront.server.conf.twig

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-11367
- Updated GLUE_STOREFRONT application with FE_HOST and FE_PORT.

SC-11367: FE_HOST and FE_PORT are absent in GLUE_STOREFRONT

---

docs/07-deploy-file/02-deploy.file.reference.v1.md

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-9864
- https://github.com/spryker/docker-php/pull/48
- Updated documentation with new `xhprof` PHP extension.

SC-9864: Add xhprof extension into the php docker containers only for dev environment

---

docs/06-configuring-services.md

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-11505
Suite-nonsplit PR: https://github.com/spryker/suite-nonsplit/pull/7398
RG: https://release.spryker.com/release-groups/view/4554
- Documentation adjustments

SC-11505: Docker SDK: unable to run browser tests against Zed locally

---

.github/workflows/b2b-b2c-demo-shop-tests.yml
.github/workflows/deploy-file-builder-tests.yml

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-11973
Replace PHP 7.4 with PHP 8.1 into CI
- update platform images for functional tests to **spryker/php:8.1-alpine3.16** and **spryker/php:8.1-debian** 
- update platform images for glue tests to **spryker/php:8.1-alpine3.16** and **spryker/php:8.1-debian**

SC-11973 CI. Replace PHP 7.4 with PHP 8.1

---

context/jenkins/export/jenkins.docker.xml.twig

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-12132
- Commands in jenkins.php will not be escaped in the cloud environment.

Added raw filter for the scheduler jobs

---

bin/environment/docker.sh
generator/src/templates/deploy.bash.twig

This PR fixes xdebug within Windows WSL systems 
Within Windows WSL systems, the env variable SPRYKER_XDEBUG_HOST_IP is not set correctly. For xdebug to work, the value should be host.docker.internal
This is a known issue
Another branch with an attempted fix exists, https://github.com/spryker/docker-sdk/tree/custom-xdebug-host-ip but this PR has been stale for quite some time. The difference between that Fix, and mine, is that with my fix everything works, and NO extra variables, or changes to the deploy file is introduced, making the change quite simple to understand

Fix WSL XDEBUG IP Detection

---

generator/src/templates/nginx/http/glue-backend.server.conf.twig
generator/src/templates/nginx/http/glue-storefront.server.conf.twig

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-12536
- Introduced `SPRYKER_GLUE_BACKEND_APPLICATION_CORS_ALLOW_ORIGIN` to store `cors-allow-origin` for `GlueBackend` application.
- Introduced `SPRYKER_GLUE_STOREFRONT_APPLICATION_CORS_ALLOW_ORIGIN ` to store `cors-allow-origin` for `GLUE_STOREFRONT` application.

GlueBackend and GlueStorefront CORS environment variables

---

bin/service/database/mysql.sh

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-12623
-  Fixed the behavior when `cli` is not running inside CI.

service "cli" is not running container #1

---

generator/src/templates/nginx/http/gateway/glue.server.conf.twig
images/common/cli/Dockerfile

Problem 1. Sometimes within CI CLI container is not still ready when gateway (nginx) container starts. That makes nginx configuration invalid as proxy_pass demands immediate resolving of IP.
```
spryker_ci_gateway_1              /docker-entrypoint.sh ngin ...   Exit 1                                                                                            
ubuntu@ip-172-31-20-107:~/build$ docker logs spryker_ci_gateway_1
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf …
```

Fixed: Gateway container runs regardless CLI containers is not ready yet

---

context/jenkins/export/entrypoint.sh
context/jenkins/export/nr-credentials.xml
images/common/services/jenkins/export/Dockerfile

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-13145
- copied nr-credentials into Jenkins Dockerfile 
- extended entrypoint for Jenkins image with using global credentials

SC-13145 Jenkins backed images doesn't provision "(global)" credentials

---

context/php/php-fpm.d/worker.conf
docs/07-deploy-file/02-deploy.file.reference.v1.md
generator/src/templates/env/pm/php-fpm.env.twig
generator/src/templates/nginx/conf.d/frontend.default.conf.twig

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-13038
Was added the ability for configuration:
- `groups: applications: application: http: timeout`
- `groups: applications: application: limits: request-terminate-timeout`

SC-13038: Introduced ability to configure Nginx and PHP-FPM timeout options. 

---

bin/lib/bool.sh
bin/sdk/images/common.sh
images/common/cli/Dockerfile

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-15697
- adjusted Blackfire client install process in CLI depending on enabling backfire PHP extension
- changed download tool from CURL to Wget for Blackfire client

SC-15697: Failed to download blackfire

---

generator/src/templates/nginx/conf.d/frontend.default.conf.twig

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-17416

Сould not build variables_hash, you should increase variables_hash_bucket_size: 64.

---

generator/src/templates/terraform/environment.tf.twig

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-16432
- environement.tf generates with uppercase when only the lowercase is available.

Generates environement.tf application name in lowercase

---

generator/src/templates/nginx/http/backend-gateway.server.conf.twig

- Ticket/Issue: https://spryker.atlassian.net/browse/CC-32874
During the creation of MR request, we have a requirement to send emails to merchant.
This mail should contain a link from the merchant portal app, unf, `backend-gateway` app doesn't contain `SPRYKER_MP_HOST` env. 
- Extended `backend-gateway` Nginx configuration with `merchant-portal` fastcgi params: `SPRYKER_MP_HOST`  and `SPRYKER_MP_PORT` if `merchant-portal` application is defined.

Extend Backend Gateway application with MerchantPortal host and port.

---

generator/src/templates/service/jenkins/default/jenkins.yml.twig

If Jenkins version isn't specified in the deploy file, the build will fail for ARM envs with next error message:
> Running generator 
> Service version compatibility errors:
>  * `scheduler` service with `jenkins` engine and 2.176 version are unsupported on ARM architecture.
> Please check documentation.
Bumped Jenkins default version.

Bump the default version of the Jenkins service

---

README.md
docs/06-configuring-services.md
generator/deploy-file-generator/templates/environment/dev/services.deploy.template.yml
generator/src/templates/service/mysql/mariadb-10.11/mysql.yml.twig

This is just a short Pull Request which supports a new version of MariaDB (10.11) which is required for our project. 
Would be great to have this in docker/sdk core instead of using a fork

Add DB support for MariaDB version 10.11

---

generator/project-data/src/DataBuilder/MultiStore/Executor/StoreSpecific/StoreSpecificBrokerExecutor.php
generator/project-data/src/DataBuilder/MultiStore/Executor/StoreSpecific/StoreSpecificKeyValueStoreExecutor.php
generator/project-data/src/DataBuilder/MultiStore/Executor/StoreSpecific/StoreSpecificSessionExecutor.php

- Ticket/Issue: none
A non-existing structure is examined in a condition that makes its result always true and therefore further processing is skipped
- Replaced a variable with the existing one in the conditions of the files:
`generator/project-data/src/DataBuilder/MultiStore/Executor/StoreSpecific/StoreSpecificBrokerExecutor.php`
`generator/project-data/src/DataBuilder/MultiStore/Executor/StoreSpecific/StoreSpecificKeyValueStoreExecutor.php`
`generator/project-data/src/DataBuilder/MultiStore/Executor/StoreSpecific/StoreSpecificSessionExecutor.php`

Fix generator multi store store specific executor conditions

---

images/common/cli/Dockerfile

- Ticket/Issue: https://spryker.atlassian.net/browse/SC-21731
- Fix the behavior when the NPM cannot be installed due to the missed `gyp`.

SC-21731: Extend Cli image with `py3-setuptools` and `build-base` packages

---

README.md
ci/deploy.dev.yml
ci/deploy.yml
docs/06-configuring-services.md
docs/07-deploy-file/02-deploy.file.reference.v1.md
generator/deploy-file-generator/templates/environment/ci/services.deploy.template.yml
generator/deploy-file-generator/templates/environment/demo/services.deploy.template.yml
generator/deploy-file-generator/templates/environment/dev/services.deploy.template.yml
generator/src/templates/nginx/http/gateway/mailpit.server.conf.twig
generator/src/templates/service/mailpit/default/mailpit.yml.twig
generator/src/templates/service/mailpit/latest/mailpit.yml.twig
generator/src/templates/service/mailpit/v1.22/mailpit.yml.twig

MailHog is dead (https://github.com/mailhog/MailHog/issues/442#issuecomment-1493415258), Mailpit is the active and maintained successor including features like viewing attachments in the preview of the emails.
- https://github.com/mailhog/MailHog/issues/442#issuecomment-1493415258
- Introduces Mailpit as standard mail-catcher

Adds Mailpit mail-catcher

---

generator/src/templates/nginx/http/proxy/reverse-proxy.conf.twig

- Ticket/Issue: SF-64390
Enables passing of the server name through [TLS Server Name Indication extension](http://en.wikipedia.org/wiki/Server_Name_Indication) (SNI, RFC 6066) when establishing a connection with the proxied HTTPS server.
Added proxy_ssl_server_name directive.

Introduced proxy_ssl_server_name directive

---

context/nginx/nginx.original.conf
context/nginx/nginx.with.stream.conf
generator/src/templates/nginx/http/server.conf.twig

Previous log_format example: 
```
11.11.11.11 - - [06/Apr/2025:21:28:41 +0000] "GET /store/switch?store=OST&referer-url=/cs/search?q=kick+buttowski HTTP/1.1" 302 366 "-" "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36" 
``` 
New log_format example: 
```
11.11.11.11 - - [08/Apr/2025:08:21:16 +0000] "GET /cs/search?q=outdoor%20kitchen&page=1 HTTP/1.1" 200 165243 "-" "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36" shop.my.shop 1.378 http/-/- 1.380 10.106.6.107:1234
``` 
The latter one improves the debugging experience. New fields are appended to the end of the list ensuring backward-compatibility. …

feat: Enhance Nginx log_format

---

images/common/services/tideways/Dockerfile

We at Tideways started publishing containers for our daemon and PHP extension last year to ensure easier integration in docker setups and to make it easy to keep versions updated
We make available an image supporting mac and Linux on x86 and ARM at: https://github.com/tideways/container-images/pkgs/container/daemon
This PR uses that image over the classic install way via apt. It's faster and will ensure up to do date versions easier and in a more docker supported way.
The effective changes of this PR are minimal, with a change in hostname and that the daemon will now listen to IPv6 as well as IPv4
```
--hostname=tideways -> --hostname=tideways-daemon
--address=0.0.0.0:9135 -> --address=[::]:9135
```
https://support.tideways.com/documentation/setup/installation/docker-with-compose.html#tide …

Prefer tideways published docker container over custom container
